import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SpinnerProvider } from './spinner/SpinnerContext';  // SpinnerContext'i import et
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';
import CartProvider from "./provider/CartProvider";
import { Toaster } from "react-hot-toast";
import React from "react"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "TechSepet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Raleway:ital,wght@0,100..900&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster position="top-right" reverseOrder={false} />

        {/* SpinnerProvider ve CartProvider'ı doğru şekilde sarmalıyız */}
        <SpinnerProvider>
          <CartProvider>
            <div className="flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-grow">
                {children}
              </main>
              <Footer />
            </div>
          </CartProvider>
        </SpinnerProvider>

      </body>
    </html>
  );
}
